assignment1:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1
      extensions: [httpfs] 
      settings:
        s3_endpoint: "{{ env_var('S3_ENDPOINT','minio:9000') }}"
        s3_url_style: path
        s3_use_ssl: false
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"

  target: dev
